# Site settings
title: Matt Cho
email: dongukcho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattcho.github.io/" # the base hostname & protocol for your site
twitter_username: matt_dcho
github_username:  mattcho

# Build settings
markdown: kramdown
